### ISSUE TITLE
About the shell that will interpreted the script

### ISSUE THREAD

**Issue by alancaldas84** [paoloap/zaread#16]
First, thanks for your script, it has been very helpful.

One question: I use debian, in it the path /bin/sh é um atalho para /bin/dash. This interpreter is pretty short and doesn't understanding things like [[ ]], so zared doesn't work in it. Is there a way for the script to be more compatible with different distributions?

**Comment by erwin** [comment]
Same on void-linux.

Why not just depend on `#!/bin/bash` if that's the shell the script is written for?

Porting it to work on dash would probably be a fair amount of work, since this already depends on hugly large packages like LibreOffice and Calibre, is anything gained from the effort to work on a minimal shell?

**Comment by Juliaria08** [comment]
Yep, zaread is using `#!/bin/sh` and seems like they expect it to be linked to `/bin/bash` so it'd be a better idea to just put `#!/bin/bash` as writing `#!/bin/sh` (normally in certain sense implies posix compliance), as the `[[ ]]` aren't supported by posix.

**Comment by iuliandita** [comment]
The idea is to make it fully POSIX compliant, and we have a large PR (#19), it's just tricky to merge it, as there are a lot of conflicts. I'll try to take the time this week to do it.

**Comment by iuliandita** [comment]
#19 was merged, the shell should not be an issue anymore.
